In [1]:
import pandas as pd 
import numpy as py 
import os

In [15]:
#Importing our data sets 
current_living_sags = "Current_Living_Sags.csv"

deceased_sags = "Final_Dead_Sags.csv"

full_history = "Full_His_Alive_Dead.csv"


#Living Saguaro Data Set 
living_df = pd.read_csv(current_living_sags)

living_df

,Accession/Planting,Most Recent Inventory Date,Status,Inventory Note,Most Recent Measurement Date,Height,Height Unit,Measurement Note,Inventory Latitude,Inventory Longitude
0,1966-8295-01-1,2/26/2020 13:53,Alive,"Saguaro Inventory 2020, VN, 2/26/20.",2/26/2020 13:53,20.3,feet,"Measured height during Saguaro Inventory 2020,...",33.460439,-111.944229
1,1970-1021-01-1,2/26/2020 13:54,Alive,"Saguaro Inventory 2020, VN, 2/26/20.",2/26/2020 13:54,22.3,feet,"Measured height during Saguaro Inventory 2020,...",33.460277,-111.944828
2,1970-9909-01-1,2/26/2020 13:52,Alive,"Saguaro Inventory 2020, VN, 2/26/20.",2/26/2020 13:52,25.1,feet,"Measured height during Saguaro Inventory 2020,...",33.460224,-111.944345
3,1971-0130-01-1,2/26/2020 13:52,Alive,"Saguaro Inventory 2020, VN, 2/26/20.",2/26/2020 13:52,8.6,feet,"Measured height during Saguaro Inventory 2020,...",33.459941,-111.942774
4,1972-0180-01-1,3/29/2019 19:33,Alive,"Saguaro Inventory 2019, VN, 2/15/19",2/27/2015 0:00,6.0,feet,0 arms. 0 buds.,33.460900,-111.944853
...,...,...,...,...,...,...,...,...,...,...
1092,2020-0150-01-4,2/26/2020 13:45,Alive,"Saguaro Inventory 2020, VN, 2/26/20.",2/26/2020 13:45,0.2,feet,"Measured height during Saguaro Inventory 2020,...",33.457232,-111.942867
1093,2020-0150-01-5,2/26/2020 13:45,Alive,"Saguaro Inventory 2020, VN, 2/26/20.",2/26/2020 13:45,0.2,feet,"Measured height during Saguaro Inventory 2020,...",33.461001,-111.944039
1094,2020-0150-01-6,2/26/2020 13:45,Alive,"Saguaro Inventory 2020, VN, 2/26/20.",2/26/2020 13:45,0.9,feet,"Measured height during Saguaro Inventory 2020,...",33.460382,-111.946088
1095,2020-0150-01-7,3/27/2020 0:00,Alive,NaN,3/27/2020 0:00,5.0,inches,NaN,33.461954,-111.946868
1096,2020-0150-01-8,9/3/2020 22:35,Alive,NaN,9/3/2020 0:00,2.5,inches,NaN,33.462076,-111.943942

In [21]:
#Starting to clean the first data frame 
living_df = living_df.dropna(subset=['Inventory Note','Measurement Note'])

living_df["Accession/Planting"].nunique()

1072

In [23]:
#Deceased Saguaros 
deceased_df = pd.read_csv(deceased_sags,encoding='cp1252')

deceased_df = deceased_df.dropna(subset=['Inventory Note','Measurement Date','Height','Height Unit','Measurement Note'])

deceased_df

,Accession/Planting,Inventory Date,Status,Inventory Note,Measurement Date,Height,Height Unit,Measurement Note
7,1966-8304-01-1,9/1/2015 0:00,Dead,Not caged. No herbivory. Uprooted completely d...,2/25/2015 0:00,28.95,feet,2 arms. 0 buds.
18,1976-0379-01-19,3/23/2016 0:00,Dead,This plant has never been mapped during the sa...,2/25/2013 21:09,15.90,feet,0 arms. Sg&cs
28,1978-0542-01-12,2/17/2017 0:00,Dead,Not caged. Old herbivory. No date. Found dead...,1/4/2013 16:55,20.60,feet,1 bud. 8 arms. jbt
47,1982-0006-06-11,11/16/2017 0:00,Dead,Caged. Old herbivory. Undated. Saguaro Invento...,2/23/2015 0:00,19.10,feet,3 arms. 0 buds.
69,1985-0254-01-13,9/26/2018 0:00,Dead,"From state of decay, likely fell before or at ...",3/5/2015 0:00,23.00,feet,1 arm. 0 buds.
...,...,...,...,...,...,...,...,...
242,2013-0266-01-8,2/14/2017 0:00,Dead,"Relocated due to bed redesign, 2016. Found de...",2/11/2013 17:03,4.10,feet,0 arms. sg&cs
244,2013-1313-01-1,3/9/2016 0:00,Dead,Not caged. No herbivory. 2/15.,2/23/2015 0:00,26.50,inches,0 arms. 0 buds.
249,2015-0151-01-10,3/9/2016 0:00,Dead,Not caged. Recent herbivory. 2/15.,3/11/2015 0:00,7.50,inches,0 arms. 0 buds.
250,2015-0152-01-1,9/27/2017 0:00,Dead,Not caged. No herbivory. Undated. Inventoried ...,2/27/2015 0:00,8.60,feet,0 arms. 1 bud.
253,2016-0042-01-4,3/7/2018 0:00,Dead,Declined from excellent condition to skeleton ...,3/23/2017 20:42,0.38,feet,"Measured during Saguaro Inventory 2017, VN, 2/..."

In [29]:
#Full history of Saguaros 
full_df = pd.read_csv(full_history,encoding='cp1252')

full_df =  = full_df.dropna(subset=['Inventory Note','Measurement Date','Height','Height Unit','DBH','Measurement Note'])

full_df

,Accession Planting,Inventory Date,Status,Condition,Inventory Note,Measurement Date,Height,Height Unit,DBH,DBH Unit,Measurement Note
0,2020-0589-10-0,9/17/2020 0:00,Dormant,Good,accessioned,NaN,NaN,NaN,NaN,NaN,NaN
1,2020-0589-10-0,9/18/2020 17:27,Dormant,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2020-0588-10-0,9/17/2020 0:00,Dormant,Good,Accessioned,NaN,NaN,NaN,NaN,NaN,NaN
3,2020-0588-10-0,9/18/2020 17:27,Dormant,Good,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2020-0587-10-0,9/17/2020 0:00,Dormant,Good,Accessioned,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
13850,1947-1548-01-1,6/17/2009 0:00,Alive,NaN,Inventoried,NaN,NaN,NaN,NaN,NaN,NaN
13851,1947-1548-01-1,7/9/2012 0:00,Alive,NaN,NOTE: This inventory date was found to be inva...,NaN,NaN,NaN,NaN,NaN,NaN
13852,1947-1548-01-1,11/28/2012 12:16,Alive,NaN,NOTE: This inventory date was found to be inva...,NaN,NaN,NaN,NaN,NaN,NaN
13853,1947-1548-01-1,12/17/2012 0:00,Dead,NaN,NOTE: This inventory date was found to be inva...,NaN,NaN,NaN,NaN,NaN,NaN
13854,1947-1548-01-1,1/31/2013 0:00,Dead,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN